pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'dir'
                bat 'zip -r ctekUI-1.zip .'
                bat 'dir'
            }
        }

        stage('Deploy to Artifactory') {
            steps {
                rtUpload (
                    serverId: 'artifactory',
                    spec: '''{
                        "files": [
                            {
                                "pattern": "ctekUI-1.zip",
                                "target": "npm-local/com/ui/test/"
                            }
                        ]
                    }'''
                )
            }
        }
        stage('Docker Build and push'){
            steps {
                script {
                    def dockerImageName = 'ctekui-1-image'
				      def dockerTagName = 'latest'
                      def dockerImageFullName = "${dockerImageName}:${dockerTagName}"


					  bat "docker login -u shiva3021 -p dckr_pat_LNb28VupU4jFKyJTySUd8If4XQ4"
					  
					  bat "docker tag ${dockerImageFullName} shiva3021/${dockerImageFullName}"
					  
					  bat "docker push shiva3021/${dockerImageFullName}"
                }
            }
        }
        
    }
}
